// <auto-generated />
using System;
using Expenas_Online.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Expenas_Online.Migrations
{
    [DbContext(typeof(InfoBuildingContext))]
    [Migration("20220718122012_infoBuildingMigracionInicial")]
    partial class infoBuildingMigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Expenas_Online.Entities.Building", b =>
                {
                    b.Property<int>("Floor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Floor");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("Expenas_Online.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingFloor")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Debt")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingFloor");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("Expenas_Online.Models.UnitDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingFloor")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Debt")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingFloor");

                    b.ToTable("UnitDto");
                });

            modelBuilder.Entity("Expenas_Online.Entities.Floor", b =>
                {
                    b.HasOne("Expenas_Online.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingFloor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Expenas_Online.Models.UnitDto", b =>
                {
                    b.HasOne("Expenas_Online.Entities.Building", null)
                        .WithMany("Units")
                        .HasForeignKey("BuildingFloor");
                });

            modelBuilder.Entity("Expenas_Online.Entities.Building", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
