// <auto-generated />
using System;
using ExpensasOnline.API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Expenas_Online.Migrations
{
    [DbContext(typeof(InformacionPisosContext))]
    [Migration("20220830220806_prueba2")]
    partial class prueba2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Expenas_Online.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "mati123",
                            Rol = 0,
                            UserName = "matias"
                        },
                        new
                        {
                            Id = 2,
                            Password = "luca123",
                            Rol = 0,
                            UserName = "luca"
                        });
                });

            modelBuilder.Entity("ExpensasOnline.API.Entities.Piso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pisos");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("ExpensasOnline.API.Entities.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Deuda")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PisoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PisoId");

                    b.ToTable("Unidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deuda = 5500f,
                            Nombre = "Sauan Matias",
                            PisoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Deuda = 55650f,
                            Nombre = "Pecorelli Luca",
                            PisoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Deuda = 55045540f,
                            Nombre = "Lucarini Gabriel",
                            PisoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Deuda = 55300f,
                            Nombre = "Sanchez Claudia",
                            PisoId = 2
                        },
                        new
                        {
                            Id = 5,
                            Deuda = 5500f,
                            Nombre = "Bolaños Roberto",
                            PisoId = 3
                        },
                        new
                        {
                            Id = 6,
                            Deuda = 553400f,
                            Nombre = "Urushima Gabriel",
                            PisoId = 3
                        });
                });

            modelBuilder.Entity("ExpensasOnline.API.Entities.Unidad", b =>
                {
                    b.HasOne("ExpensasOnline.API.Entities.Piso", "Piso")
                        .WithMany("Unidad")
                        .HasForeignKey("PisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piso");
                });

            modelBuilder.Entity("ExpensasOnline.API.Entities.Piso", b =>
                {
                    b.Navigation("Unidad");
                });
#pragma warning restore 612, 618
        }
    }
}
