// <auto-generated />
using Expenas_Online.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Expenas_Online.Migrations
{
    [DbContext(typeof(InfoBuildingContext))]
    partial class InfoBuildingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Expenas_Online.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Building");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "asd"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "sss"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "eeeeo"
                        });
                });

            modelBuilder.Entity("Expenas_Online.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Debt")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Debt = 3000f,
                            Nombre = "Carla"
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            Debt = 9000f,
                            Nombre = "Roberto"
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 1,
                            Debt = 8000f,
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 1,
                            Debt = 2000f,
                            Nombre = "s"
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 2,
                            Debt = 1000f,
                            Nombre = "a"
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = 2,
                            Debt = 4000f,
                            Nombre = "aeae"
                        });
                });

            modelBuilder.Entity("Expenas_Online.Entities.Floor", b =>
                {
                    b.HasOne("Expenas_Online.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Expenas_Online.Entities.Building", b =>
                {
                    b.Navigation("Floors");
                });
#pragma warning restore 612, 618
        }
    }
}
